var initIndex = function () {

	var initBT = function () {

			var str='';
			str+='﻿ <div id="Header_creative" >';
			str+='        <a href="#" class="creative-menu-toggle"><i class="icon-menu-fine"></i></a>';
			str+='        <div class="creative-social">';
			str+='        </div>';
			str+='        <div class="creative-wrapper">';
			str+='';
			str+='            <div id="Top_bar">';
			str+='                <div class="one clearfix">';
			str+='                    <div class="top_bar_left">';
			str+='                        <div class="logo">';
			str+='                            <a id="logo" href="http://www.befootball365.com/" data-height="106" data-padding="60"><img class="logo-main scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/retina-football2.png" alt="首页" data-retina="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2.png" data-height="212" data-no-retina><img class="logo-sticky scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/retina-football2.png" data-retina="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2.png" alt="首页" data-height="212" data-no-retina><img class="logo-mobile scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/retina-football2.png" data-retina="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2.png" alt="首页" data-height="212" data-no-retina><img class="logo-mobile-sticky scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/retina-football2.png" data-retina="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2.png" alt="首页" data-height="212" data-no-retina></a>';
			str+='                        </div>';
			str+='                        <div class="menu_wrapper">';
			str+='                            <nav id="menu">';
			str+='                                <ul id="menu-main-menu" class="menu menu-main">';
			str+='                                    <li class=" current-menu-item page_item current_page_item">';
			str+='                                        <a href="http://www.befootball365.com/"><span>首页</span></a>';
			str+='                                    </li>';
			str+='                                    <li>';
			str+='                                        <a href="#ljwm" ><span>了解我们</span></a>';
			str+='                                    </li>';
			str+='                                    <li>';
			str+='                                        <a href="feature.html"><span>软件特征</span></a>';
			str+='                                    </li>';
			str+='                                    <li>';
			str+='                                        <a href="news/2019-news.html"><span>足球分析</span></a>';
			str+='                                    </li>';
			str+='                                     <li>';
			str+='                                        <a href="http://www.befootball365.com/history/ycs.html"><span>预测记录</span></a>';
			str+='                                    </li>';
			str+='                                    <li>';
			str+='                                        <a href="#download"><span>下载软件</span></a>';
			str+='                                    </li>';
			str+='                                    <li>';
			str+='                                        <a href="#Footer"  ><span>联系我们</span></a>';
			str+='                                    </li>';
			str+='                                </ul>';
			str+='                            </nav><a class="responsive-menu-toggle" href="#"><i class="icon-menu-fine"></i></a>';
			str+='                        </div>';
			str+='                    </div>';
			str+='                </div>';
			str+='            </div>';
			str+='        </div>';
			str+='    </div>';
			str+='    <div id="Wrapper">';
			str+='        <div id="Header_wrapper" >';
			str+='            <header id="Header">';
			str+='                <div class="mfn-main-slider" id="mfn-rev-slider">';
			str+='                    <div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">';
			str+='                        <div id="rev_slider_1_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.8.3">';
			str+='                            <ul>';
			str+='                                <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-rotate="0" data-saveperformance="off" data-data-param1';
			str+='                                    data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>';
			str+='                                    <img src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic1.jpg" alt="足球分析" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="8" class="rev-slidebg" data-no-retina>';
			str+='                                    <div class="tp-caption tp-resizeme rs-parallaxlevel-4" id="slide-1-layer-1" data-x="50" data-y="230" data-width="[\'auto\']" data-height="[\'auto\']" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\'';
			str+='                                        data-textAlign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 24px; line-height: 22px; font-weight: 400; color: #fff; letter-spacing: 5px;font-family:Oswald;">';
			str+='                                       	 欢迎访问';
			str+='                                    </div>';
			str+='                                    <div class="tp-caption tp-resizeme rs-parallaxlevel-4" id="slide-1-layer-2" data-x="50" data-y="271" data-width="[\'auto\']" data-height="[\'auto\']" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\'';
			str+='                                        data-textAlign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 60px; line-height: 64px; font-weight: 600; color: #fa1e3d; letter-spacing: 2px;font-family:Oswald;">';
			str+='                                        	BeFootBall 足球分析软件';
			str+='                                        <br>  专业分析师亚盘推荐';
			str+='                                    </div>';
			str+='                                    <div class="tp-caption tp-resizeme rs-parallaxlevel-4" id="slide-1-layer-3" data-x="50" data-y="450" data-width="[\'auto\']" data-height="[\'auto\']" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\'';
			str+='                                        data-textAlign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; white-space: nowrap; font-size: 20px; line-height: 30px; font-weight: 300; color: #fff; letter-spacing: 1px;font-family:Oswald;">';
			str+='                                         		专为足球爱好者和投注者设计';
			str+='                                        <br> 提供即将到来比赛的亚盘预测、走地大球预测';
			str+='                                        <br> 每日比赛由职业分析师精心推荐，帮助足球投资者做出正确决策';
			str+='                                        ';
			str+='                                        ';
			str+='                                    </div>';
			str+='                                    <a class="tp-caption rev-btn tp-resizeme rs-parallaxlevel-4" href="#ljwm" target="_self" id="slide-1-layer-4" data-x="49" data-y="585" data-width="[\'auto\']" data-height="[\'auto\']" data-type="button" data-actions data-responsive_offset="on" data-frames=\'[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(223,24,52);bs:solid;bw:0 0 0 0;"}]\'';
			str+='                                        data-textAlign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[15,15,15,15]" data-paddingright="[35,35,35,35]" data-paddingbottom="[15,15,15,15]" data-paddingleft="[35,35,35,35]" style="z-index: 8; white-space: nowrap; font-size: 16px; line-height: 22px; font-weight: 400; color: #fff; letter-spacing: px;font-family:Oswald;background-color:rgb(250,30,61);border-color:rgba(0,0,0,1);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;">更多关于我们的信息 </a>';
			str+='                                </li>';
			str+='                            </ul>';
			str+='                            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>';
			str+='                        </div>';
			str+='                    </div>';
			str+='                </div>';
			str+='            </header>';
			str+='        </div>';
			str+='        <div id="Content">';
			str+='            <div class="content_wrapper clearfix">';
			str+='                <div class="sections_group">';
			str+='                    <div class="entry-content">';
			str+='                        <div class="section mcb-section mcb-section-0gasmdjvr no-margin-h no-margin-v equal-height-wrap" style="padding-top:0px;padding-bottom:0px;background-color:">';
			str+='                            <div class="section_wrapper mcb-section-inner">';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-0301oxq7t one-second valign-top move-up clearfix" style="margin-top:-150px" data-mobile="no-up">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-uqhf6f91h one column_placeholder">';
			str+='                                            <div class="placeholder">';
			str+='                                                &nbsp;';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-015jxm1qw one-fourth valign-middle bg-cover move-up clearfix" style="padding:40px 0 40px;margin-top:-150px;background-image:url(https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic20.jpg);background-repeat:no-repeat;background-position:center;" data-mobile="no-up">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-97ofdg86a one column_image">';
			str+='                                            <div class="image_frame image_item no_link scale-with-grid alignright no_border">';
			str+='                                                <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic21.png" alt="足球推荐">';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-w72g8yfvt one-fourth valign-top move-up clearfix" style="padding:40px 30px 25px;background-color:#fff;margin-top:-150px" data-mobile="no-up">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-6253jrmkv one column_column">';
			str+='                                            <div class="column_attr clearfix align_center">';
			str+='                                                <h6 style="display: inline-block; background: #000; padding: 5px 15px;">分析师推荐时间</h6>';
			str+='                                                <p style="color: #1a1a1a;">';
			str+='                                                   			每日17点准时更新.';
			str+='                                                </p>';
			str+='                                                <p>';
			str+='                                                    <a href="http://www.befootball365.com/history/ycs.html">预测记录</a>';
			str+='                                                </p>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                            </div>';
			str+='                        </div>';
			str+='                        <div id="ljwm" class="section mcb-section mcb-section-n44qtd9qx equal-height-wrap" style="padding-top:110px;padding-bottom:70px;background-color:">';
			str+='                            <div class="section_wrapper mcb-section-inner">';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-5wgtd5vzj one-second valign-middle clearfix" >';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-xofz0slop one column_image">';
			str+='                                            <div class="image_frame image_item no_link scale-with-grid aligncenter no_border">';
			str+='                                                <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic2.png" alt="了解我们">';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-1txcbkido one-second valign-middle clearfix" style="padding:0 0 0 5%">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-ml27fl39k one column_column">';
			str+='                                            <div class="column_attr clearfix">';
			str+='                                                <div class="image_frame image_item no_link scale-with-grid alignnone no_border">';
			str+='                                                    <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic3.png" alt="了解我们">';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 20px;">';
			str+='                                                <h4>关于</h4>';
			str+='                                                <h1 class="themecolor">BeFootBall</h1>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 20px;">';
			str+='                                                <p>';
			str+='                                                    		使用BeFootBall，您将获得2-4场准确的亚盘赛事预测结果。<br>';
			str+='                                                    		BeFootBall职业足球专家团队对即将到来的比赛进行预测，并通过软件以非常方便的形式呈现在您的桌面上。<br>';
			str+='                                                    		如果您想节省在足球预测上花费的时间或获取更为准确的比赛预测结果，BeFootBall足球分析软件是您的正确选择！';
			str+='                                                </p>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 25px;">';
			str+='                                                <a class="button button_size_2 button_theme button_js" href="feature.html" target="_blank" ><span class="button_label">软件特征</span></a>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                            </div>';
			str+='                        </div>';
			str+='                        ';
			str+='                         <div class="section mcb-section mcb-section-z2fe7wnrc" >';
			str+='                            <div class="section_wrapper mcb-section-inner">';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-y7pij1p1z one valign-top clearfix">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-fbupxujcq two-fifth column_column">';
			str+='                                            <div class="column_attr clearfix">';
			str+='                                                <h3>BeFootBall';
			str+='                                                    <br> 软件介绍</h3>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-70cwx3d6r one column_divider">';
			str+='                                            <hr class="no_line" style="margin: 0 auto 100px;" />';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-rvmkosy32 one valign-top clearfix">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-43bwjptya one-second column_image">';
			str+='                                            <div class="image_frame image_item no_link scale-with-grid no_border">';
			str+='                                                <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/hosting2-offer-icon-1.png" alt="软件介绍" />';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-ych3v6wis one-second column_column">';
			str+='                                            <div class="column_attr clearfix" style=" padding:0 5%;">';
			str+='                                                <h3>为什么使用BeFootBall?</h3>';
			str+='                                                <p>';
			str+='                                                   	 数据时代，软件已经应用于我们生活的各个方面。包括预测未来事件或行为：从人类社会发展和医疗预测，甚至是Bet公司的水位预测。';
			str+='                                                </p>';
			str+='                                                <p>';
			str+='                                                   	Bet公司通过使用软件来预测匹配并计算其水位。不同于过去使用数据量检测系统，这是他们巨大优势（即利润）的来源。';
			str+='                                                </p>';
			str+='                                                <p>';
			str+='                                                   	无论个人对比赛信息掌握的多么全面，对于下注者来说，独自对抗Bet公司都是一个巨大的难题。只有使用BeFootBall专业软件才能获得长期利润，并战胜Bet公司。';
			str+='                                                </p>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 15px;" />';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-l0qsw0nat one column_divider">';
			str+='                                            <hr class="no_line" style="margin: 0 auto 100px;" />';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-8ax4f6xqj one valign-top clearfix">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-rxkxkblqn one-second column_image">';
			str+='                                            <div class="image_frame image_item no_link scale-with-grid no_border">';
			str+='                                                <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/hosting2-offer-icon-2.png" alt="软件介绍"/>';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-gignne7dk one-second column_column">';
			str+='                                            <div class="column_attr clearfix" style=" padding:0 5%;">';
			str+='                                                <h3>高命中率预测软件</h3>';
			str+='                                                <p>';
			str+='                                                 	   我们很自豪地向您展示目前市场上高命中率的预测软件！如果这个准确率不满足你的要求，那么您应该停止寻找其它足球分析软件了！';
			str+='                                                </p>';
			str+='                                                <p>';
			str+='                                                   	 我们拥有累积10年的足球比赛分析经验，并不断进行改进。';
			str+='                                                </p>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 15px;" />';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-r47c8gdq1 one column_divider">';
			str+='                                            <hr class="no_line" style="margin: 0 auto 100px;" />';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-e6ov1hdg9 one valign-top clearfix">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-n8qbc8a36 one-second column_image">';
			str+='                                            <div class="image_frame image_item no_link scale-with-grid no_border">';
			str+='                                                <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/hosting2-offer-icon-3.png" alt="软件介绍"/>';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-sta1fhqk8 one-second column_column">';
			str+='                                            <div class="column_attr clearfix" style=" padding:0 5%;">';
			str+='                                                <h3>高性能</h3>';
			str+='                                                <p>';
			str+='                                                    	虽然没有人可以正确预测所有的比赛（足球并不是总符合常我们的常规认知），';
			str+='                                                    	BeFootBall智能分析引擎被证明处于目前市场上的顶尖水平，分析师通过分析引擎与联赛经验，';
			str+='                                                    	将预测准确性提升到一个全新的领域。';
			str+='                                                </p>';
			str+='                                                <p>';
			str+='                                                    	如果你找到一个市面上更准确的分析软件，请通知我们！';
			str+='                                                </p>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 15px;" />';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-mcgqi32s5 one column_divider">';
			str+='                                            <hr class="no_line" style="margin: 0 auto 50px;" />';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                            </div>';
			str+='                        </div>';
			str+='                        ';
			str+='                        ';
			str+='                        <div id="faq" class="section mcb-section mcb-section-aa0bdfqzr"';
			str+='							style="padding-top: 110px; padding-bottom: 180px; background-color:">';
			str+='							<div class="section_wrapper mcb-section-inner">';
			str+='								<div';
			str+='									class="wrap mcb-wrap mcb-wrap-ndw4bbvui one valign-top clearfix"';
			str+='									style>';
			str+='									<div class="mcb-wrap-inner">';
			str+='										<div class="column mcb-column mcb-item-xptdcthvc one column_column">';
			str+='											<div class="column_attr clearfix">';
			str+='												<h4>常见问题</h4>';
			str+='											</div>';
			str+='										</div>';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-uov4hike3 one column_divider">';
			str+='											<hr class="no_line" style="margin: 0 auto 40px;">';
			str+='										</div>';
			str+='									</div>';
			str+='								</div>';
			str+='								<div class="wrap mcb-wrap mcb-wrap-62zbkqdo8 one-second valign-top clearfix"';
			str+='									style="padding: 0 5% 0 0">';
			str+='									<div class="mcb-wrap-inner">';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-2yyg5i7en one-fourth column_image">';
			str+='											<div';
			str+='												class="image_frame image_item no_link scale-with-grid aligncenter no_border">';
			str+='												<div class="image_wrapper">';
			str+='													<img class="scale-with-grid"';
			str+='														src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/company5_icon5.png">';
			str+='												</div>';
			str+='											</div>';
			str+='										</div>';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-bxnfl0arn three-fourth column_column">';
			str+='											<div class="column_attr clearfix" style="padding: 0 0 0 5%;">';
			str+='												<h5 class="themecolor">每天提供多少场比赛推荐？</h5>';
			str+='												<p>我们优先考虑比赛质量而不是数量。比赛休息以及其他情况会干扰所发送比赛提示的数量。基于以往的经验，我们每天会为您提供两场精选的比赛推荐，额外的，我们会提供其他场次的推荐。</p>';
			str+='												<hr class="no_line" style="margin: 0 auto 5px;">';
			str+='											</div>';
			str+='										</div>';
			str+='									</div>';
			str+='								</div>';
			str+='								<div';
			str+='									class="wrap mcb-wrap mcb-wrap-3tz0xfrbe one-second valign-top clearfix"';
			str+='									style="padding: 0 5% 0 0">';
			str+='									<div class="mcb-wrap-inner">';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-c0f37z7y5 one-fourth column_image">';
			str+='											<div';
			str+='												class="image_frame image_item no_link scale-with-grid aligncenter no_border">';
			str+='												<div class="image_wrapper">';
			str+='													<img class="scale-with-grid"';
			str+='														src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/company5_icon2.png">';
			str+='												</div>';
			str+='											</div>';
			str+='										</div>';
			str+='										<div class="column mcb-column mcb-item-h9hu5dmbk three-fourth column_column">';
			str+='											<div class="column_attr clearfix" style="padding: 0 0 0 5%;">';
			str+='												<h5 class="themecolor">能否免费获得比赛推荐？</h5>';
			str+='												<p>足球预测需要花费大量的时间和精力，如果你想要从众多比赛中获得高质量推荐，';
			str+='                                                        	同样也需要付出更多成本。</p>';
			str+='												<hr class="no_line" style="margin: 0 auto 5px;">';
			str+='											</div>';
			str+='										</div>';
			str+='									</div>';
			str+='								</div>';
			str+='								<div class="wrap mcb-wrap mcb-wrap-yhdlclkjx one valign-top clearfix"';
			str+='									style>';
			str+='									<div class="mcb-wrap-inner">';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-nuodkp0pb one column_divider">';
			str+='											<hr class="no_line" style="margin: 0 auto 40px;">';
			str+='										</div>';
			str+='									</div>';
			str+='								</div>';
			str+='								<div';
			str+='									class="wrap mcb-wrap mcb-wrap-art6n05rr one-second valign-top clearfix"';
			str+='									style="padding: 0 5% 0 0">';
			str+='									<div class="mcb-wrap-inner">';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-fha9q17a9 one-fourth column_image">';
			str+='											<div';
			str+='												class="image_frame image_item no_link scale-with-grid aligncenter no_border">';
			str+='												<div class="image_wrapper">';
			str+='													<img class="scale-with-grid"';
			str+='														src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/company5_icon3.png">';
			str+='												</div>';
			str+='											</div>';
			str+='										</div>';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-5kt3eejk9 three-fourth column_column">';
			str+='											<div class="column_attr clearfix" style="padding: 0 0 0 5%;">';
			str+='												<h5 class="themecolor">会有固定比赛推荐吗？</h5>';
			str+='												<p>不会，为了保证预测准确性，我们不针对固定比赛进行预测。</p>';
			str+='												<hr class="no_line" style="margin: 0 auto 5px;">';
			str+='											</div>';
			str+='										</div>';
			str+='									</div>';
			str+='								</div>';
			str+='								<div';
			str+='									class="wrap mcb-wrap mcb-wrap-hed7u56gz one-second valign-top clearfix"';
			str+='									style="padding: 0 5% 0 0">';
			str+='									<div class="mcb-wrap-inner">';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-vqtzyfm6y one-fourth column_image">';
			str+='											<div';
			str+='												class="image_frame image_item no_link scale-with-grid aligncenter no_border">';
			str+='												<div class="image_wrapper">';
			str+='													<img class="scale-with-grid"';
			str+='														src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/company5_icon4.png">';
			str+='												</div>';
			str+='											</div>';
			str+='										</div>';
			str+='										<div';
			str+='											class="column mcb-column mcb-item-3g6uhjded three-fourth column_column">';
			str+='											<div class="column_attr clearfix" style="padding: 0 0 0 5%;">';
			str+='												<h5 class="themecolor">如果预测结果失败怎么样？</h5>';
			str+='												<p>就像您所知道的那样，您永远无法达到100％的准确性。';
			str+='													我们在会尽最大努力确保预测的准确性达到70％以上。如果我们的预测在某一天出现错误，我们将确保第二天重回正轨。</p>';
			str+='												<hr class="no_line" style="margin: 0 auto 5px;">';
			str+='											</div>';
			str+='										</div>';
			str+='									</div>';
			str+='								</div>';
			str+='							</div>';
			str+='						</div>';
			str+='                        ';
			str+='                         <div class="section mcb-section" style="padding-top:70px; padding-bottom:30px;">';
			str+='                            <div class="section_wrapper mcb-section-inner">';
			str+='                                <div class="wrap mcb-wrap one valign-top clearfix">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column one-third column_icon_box">';
			str+='                                            <div class="icon_box icon_position_top has_border">';
			str+='                                                <div class="icon_wrapper">';
			str+='                                                    <div class="icon">';
			str+='                                                        <i class="icon-docs"></i>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <div class="desc_wrapper">';
			str+='                                                    <h4 class="title">专注于预测结果</h4>';
			str+='                                                    <div class="desc">';
			str+='                                                      		 我们每一年在数据库中保存数百个国内和国际比赛数据，';
			str+='                                                      		 并且针对各种类型的赛事投注具有明确的性能和准确度指标，让您始终拥有更好的投注推荐。';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column one-third column_icon_box ">';
			str+='                                            <div class="icon_box icon_position_top has_border">';
			str+='                                                <div class="icon_wrapper">';
			str+='                                                    <div class="icon">';
			str+='                                                        <i class="icon-cog-line"></i>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <div class="desc_wrapper">';
			str+='                                                    <h4 class="title">收费预测</h4>';
			str+='                                                    <div class="desc">';
			str+='                                                        	为什么我们不提供免费预测？实际上，没有什么是免费的，';
			str+='                                                        	免费预测通常由Bet公司赞助，但这绝对不是你需要的。';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column one-third column_icon_box ">';
			str+='                                            <div class="icon_box icon_position_top no_border">';
			str+='                                                <div class="icon_wrapper">';
			str+='                                                    <div class="icon">';
			str+='                                                        <i class="icon-star-line"></i>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <div class="desc_wrapper">';
			str+='                                                    <h4 class="title">注意事项</h4>';
			str+='                                                    <div class="desc">';
			str+='                                                    	    谨防提供复杂的数学理论的Bet软件或系统！他们中的大多数都是假的，主要基于用户的足球经验匮乏。';
			str+='                                                       	   事实上，一个好的程序在非常简单的界面下隐藏了大量的算法，这就是BeFootBall为您呈现的效果！';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                            </div>';
			str+='                        </div>';
			str+='                        ';
			str+='                        <div class="section" id="pricingbox flv_sections_16" >';
			str+='                            <div class="section_wrapper clearfix">';
			str+='                                <div class="items_group clearfix">';
			str+='                                    <!-- One full width row-->';
			str+='                                    <div class="column one column_column">';
			str+='                                        <div class="column_attr ">';
			str+='                                            <h5 class="flv_style_4">价格列表</h5>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                    <div class="column one-third column_pricing_item">';
			str+='                                        <div class="pricing-box pricing-box-box">';
			str+='                                            <div class="plan-header">';
			str+='                                                <div class="image"><img src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/home_hosting_pricing_pic_3.png" alt="周卡价格"  />';
			str+='                                                </div>';
			str+='                                                <h4 style="color: #a8a8a8;">周卡</h4>';
			str+='                                                <div class="price">';
			str+='                                                    <sup class="currency">￥</sup><span>650</span><sup class="period">/ 周</sup>';
			str+='                                                </div>';
			str+='                                                <hr class="hr_color" />';
			str+='                                                <p class="subtitle">';
			str+='                                                    <span class="big">会员期内享受分析师私人推荐.</span>';
			str+='                                                </p>';
			str+='                                            </div>';
			str+='                                            <div class="plan-inside">';
			str+='                                                <ul style="color: #a8a8a8;">';
			str+='                                                    <li>';
			str+='                                                       	 7天使用时长';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         Windows系统';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         Android系统';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         IOS系统';
			str+='                                                    </li>';
			str+='                                                </ul>';
			str+='                                            </div>';
			str+='                                            <div class="plan-footer">';
			str+='                                                <a href="#downloadsoft" class="button button_left button_theme button_js"><span class="button_icon"><i class="icon-basket"></i></span><span class="button_label">下载购买</span></a>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                     <div class="column one-third column_pricing_item">';
			str+='                                        <div class="pricing-box pricing-box-featured pricing-box-box">';
			str+='                                            <div class="plan-header">';
			str+='                                                <div class="image"><img src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/home_hosting_pricing_pic_3.png" alt="月卡价格"  />';
			str+='                                                </div>';
			str+='                                                <h4>月卡</h4>';
			str+='                                                <div class="price">';
			str+='                                                    <sup class="currency">￥</sup><span>1500</span><sup class="period">/ 月</sup>';
			str+='                                                </div>';
			str+='                                                <hr class="hr_color" />';
			str+='                                                <p class="subtitle">';
			str+='                                                    <span class="big">会员期内享受分析师私人推荐.</span>';
			str+='                                                </p>';
			str+='                                            </div>';
			str+='                                            <div class="plan-inside">';
			str+='                                                <ul >';
			str+='                                                     <li>';
			str+='                                                        30天使用时长';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         Windows系统';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         Android系统';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         IOS系统';
			str+='                                                    </li>';
			str+='                                                </ul>';
			str+='                                            </div>';
			str+='                                            <div class="plan-footer">';
			str+='                                                <a href="#downloadsoft" class="button button_left button_theme button_js"><span class="button_icon"><i class="icon-basket"></i></span><span class="button_label">下载购买</span></a>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                    <div class="column one-third column_pricing_item">';
			str+='                                        <div class="pricing-box pricing-box-box" >';
			str+='                                            <div class="plan-header">';
			str+='                                                <div class="image"><img src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/home_hosting_pricing_pic_4.png" alt="季卡价格" />';
			str+='                                                </div>';
			str+='                                                <h4 style="color: #a8a8a8;">季卡</h4>';
			str+='                                                <div class="price">';
			str+='                                                    <sup class="currency">￥</sup><span>2300</span><sup class="period">/ 季</sup>';
			str+='                                                </div>';
			str+='                                                <hr class="hr_color" />';
			str+='                                                <p class="subtitle">';
			str+='                                                    <span class="big">会员期内享受分析师私人推荐.</span>';
			str+='                                                </p>';
			str+='                                            </div>';
			str+='                                            <div class="plan-inside">';
			str+='                                                <ul style="color: #a8a8a8;">';
			str+='                                                     <li>';
			str+='                                                        90天使用时长';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         Windows系统';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         Android系统';
			str+='                                                    </li>';
			str+='                                                    <li>';
			str+='                                                         IOS系统';
			str+='                                                    </li>';
			str+='                                                </ul>';
			str+='                                            </div>';
			str+='                                            <div class="plan-footer">';
			str+='                                                <a href="#downloadsoftware" class="button button_left button_theme button_js"><span class="button_icon"><i class="icon-basket"></i></span><span class="button_label">下载购买</span></a>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                            </div>';
			str+='                        </div>';
			str+='                        ';
			str+='                        <div class="section mcb-section mcb-section-2hzy91tdz" style="padding-top:30px;padding-bottom:30px;background-image:url(https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic10.png);background-repeat:repeat-x;background-position:center bottom;">';
			str+='                            <div class="section_wrapper mcb-section-inner">';
			str+='                            	<div class="wrap mcb-wrap mcb-wrap-nmp28afsx one valign-top clearfix" >';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-lcrw2hi3i one column_column">';
			str+='                                            <div class="column_attr clearfix align_center">';
			str+='                                                <h4 class="themecolor">赛事分析</h4>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                      ';
			str+='                                ';
			str+='                                ';
			str+='								<div class="wrap mcb-wrap mcb-wrap-0io59mubr one-second column-margin-0px valign-top clearfix" style="padding:0 2% 0 0">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-hh4y1wvqx one column_column">';
			str+='                                            <div class="column_attr clearfix align_center">';
			str+='                                                <h6 class="themecolor" style="border-top: 2px solid #fa1e3d; padding-top: 15px; display: inline-block;">比赛分析</h6>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-iwoa4nycy one column_column">';
			str+='                                            <div class="column_attr clearfix align_center" style="background-color:#f6f6f6;padding:40px 40px 25px;">';
			str+='                                                <h6><span style="color: #1a1a1a;">巴萨罗那</span>';
			str+='                                                    <br>';
			str+='                                                    <span style="color: #959eac;">莱加内斯</span></h6>';
			str+='                                                <div class="column one-third">';
			str+='                                                    <div class="image_frame image_item no_link scale-with-grid alignnone no_border">';
			str+='                                                        <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic7.png" alt="球队">';
			str+='                                                        </div>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <div class="column one-third">';
			str+='                                                    <h4 style="color: #b1b8c1; margin: 0; padding: 20px 0;"><span class="themecolor">VS</span></h4>';
			str+='                                                </div>';
			str+='                                                <div class="column one-third">';
			str+='                                                    <div class="image_frame image_item no_link scale-with-grid alignnone no_border">';
			str+='                                                        <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic9.png" alt="球队">';
			str+='                                                        </div>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 15px;">';
			str+='                                                <h6 style="color: #959eac;">2020-06-16 Valentina</h6>';
			str+='                                                <h6 style="color: #959eac;">克莱门特-伦格莱特在停赛后重新回归，因为塞缪尔-乌姆蒂蒂的健康问题，他应当替代罗纳德-阿劳霍担任中后卫...</h6>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 15px;">';
			str+='                                                <a class="button button_size_2 button_theme button_js"  href="http://www.befootball365.com/news/2019/89.html" target="_blank"><span class="button_label">查看详情</span></a>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='﻿								<div class="wrap mcb-wrap mcb-wrap-0io59mubr one-second column-margin-0px valign-top clearfix" style="padding:0 2% 0 0">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-hh4y1wvqx one column_column">';
			str+='                                            <div class="column_attr clearfix align_center">';
			str+='                                                <h6 class="themecolor" style="border-top: 2px solid #fa1e3d; padding-top: 15px; display: inline-block;">比赛分析</h6>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-iwoa4nycy one column_column">';
			str+='                                            <div class="column_attr clearfix align_center" style="background-color:#f6f6f6;padding:40px 40px 25px;">';
			str+='                                                <h6><span style="color: #1a1a1a;">博鲁阿拉瓦格拉德莫扎特</span>';
			str+='                                                    <br>';
			str+='                                                    <span style="color: #959eac;">勒沃库森</span></h6>';
			str+='                                                <div class="column one-third">';
			str+='                                                    <div class="image_frame image_item no_link scale-with-grid alignnone no_border">';
			str+='                                                        <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic7.png" alt="球队">';
			str+='                                                        </div>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <div class="column one-third">';
			str+='                                                    <h4 style="color: #b1b8c1; margin: 0; padding: 20px 0;"><span class="themecolor">VS</span></h4>';
			str+='                                                </div>';
			str+='                                                <div class="column one-third">';
			str+='                                                    <div class="image_frame image_item no_link scale-with-grid alignnone no_border">';
			str+='                                                        <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2_pic9.png" alt="球队">';
			str+='                                                        </div>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 15px;">';
			str+='                                                <h6 style="color: #959eac;">2020-06-16 Prima</h6>';
			str+='                                                <h6 style="color: #959eac;">头号得分手阿拉萨市内普莱亚早已禁赛，但是内收肌受伤被排除在外...</h6>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 15px;">';
			str+='                                                <a class="button button_size_2 button_theme button_js"  href="http://www.befootball365.com/news/2019/90.html" target="_blank"><span class="button_label">查看详情</span></a>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='';
			str+='';
			str+='                                ';
			str+='                                ';
			str+='                            </div>';
			str+='                        </div>';
			str+='                        ';
			str+='                        <div id="downloadsoft" ></div>';
			str+='                        <div id="downloadsoftware" ></div>';
			str+='                         <div id="download"  class="section mcb-section mcb-section-jlo4hi97l dark equal-height-wrap" style="padding-top:150px; padding-bottom:150px; background-color:#180d5b">';
			str+='                            <div class="section-decoration top" style="background-image:url(https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/hosting2-home-top-decor.png);height:135px"></div>';
			str+='                            <div class="section_wrapper mcb-section-inner">';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-iwcu2qu5v one-second valign-middle clearfix">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-0vl948hfw four-fifth column_column">';
			str+='                                            <div class="column_attr clearfix">';
			str+='                                                <h4>软件下载</h4>';
			str+='                                                <hr class="no_line" style="margin: 0 auto 10px;" />';
			str+='                                                <p> 下载BeFootBall！享受足球职业分析师精准推荐.<br>';
			str+='                                             		自2005年起上线，被全球足球爱好者测试使用.                  ';
			str+='                                                 </p>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-5wihz4zgd one-third column_button">';
			str+='                                            <a class="button button_size_3 button_js" href="https://share.weiyun.com/5EDa4Tv" rel="nofollow" target="_blank" style="background-color:#c4c3f7!important;color:#180d5b;"><span class="button_label">Windows</span></a>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-5wihz4zgd one-third column_button">';
			str+='                                            <a class="button button_size_3 button_js" href="https://share.weiyun.com/5Fe8CPk" rel="nofollow" target="_blank" style="background-color:#c4c3f7!important;color:#180d5b;"><span class="button_label">安卓系统</span></a>';
			str+='                                        </div>';
			str+='                                        <div class="column mcb-column mcb-item-5wihz4zgd one-third column_button">';
			str+='                                            <a class="button button_size_3 button_js" href="https://couli.cn/app.php/NDk3NA==" rel="nofollow" target="_blank" style="background-color:#c4c3f7!important;color:#180d5b;"><span class="button_label">苹果系统</span></a>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                                <div class="wrap mcb-wrap mcb-wrap-bzgkrle49 one-second valign-middle clearfix">';
			str+='                                    <div class="mcb-wrap-inner">';
			str+='                                        <div class="column mcb-column mcb-item-lp9c0thc7 one column_image">';
			str+='                                            <div class="animate" data-anim-type="fadeInUp">';
			str+='                                                <div class="image_frame image_item no_link scale-with-grid no_border">';
			str+='                                                    <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/hosting2-home-man.png" alt="软件下载"/>';
			str+='                                                    </div>';
			str+='                                                </div>';
			str+='                                            </div>';
			str+='                                        </div>';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                            </div>';
			str+='                            <div class="section-decoration bottom" style="background-image:url(https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/hosting2-home-bottom-decor.png);height:126px"></div>';
			str+='                        </div>';
			str+='                        ';
			str+='                    </div>';
			str+='                </div>';
			str+='            </div>';
			str+='        </div>';
			str+='        <footer id="Footer" class="clearfix">';
			str+='            <div class="widgets_wrapper">';
			str+='                <div class="container">';
			str+='                    <div class="column one-third">';
			str+='                        <aside class="widget_text widget widget_custom_html">';
			str+='                            <div class="textwidget custom-html-widget">';
			str+='                                <hr class="no_line" style="margin: 0 auto 10px;">';
			str+='                                <h5>联系我们</h5>';
			str+='                                <h4 class="themecolor">';
			str+='                               	 客服QQ:773294307';
			str+='								</h4>';
			str+='								  <a	target="_blank"   class="c-btn-icon c-pull-right"';
			str+='									href="http://wpa.qq.com/msgrd?v=3&uin=773294307&site=qq&menu=yes">';
			str+='									<img border="0"';
			str+='									style="text-align: center; line-height: 0; vertical-align: middle; padding: 0;"';
			str+='									src="http://wpa.qq.com/pa?p=2:773294307:51" alt="点击这里给我发消息"';
			str+='									title="点击这里给我发消息" />';
			str+='								</a>';
			str+='                            </div>';
			str+='                        </aside>';
			str+='                    </div>';
			str+='                    <div class="column one-third">';
			str+='                        <aside class="widget_text widget widget_custom_html">';
			str+='                            <div class="textwidget custom-html-widget">';
			str+='                                <div class="image_frame image_item no_link scale-with-grid aligncenter no_border">';
			str+='                                    <div class="image_wrapper"><img class="scale-with-grid" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/janq/be/img/football2.png" alt="联系我们">';
			str+='                                    </div>';
			str+='                                </div>';
			str+='                            </div>';
			str+='                        </aside>';
			str+='                    </div>';
			str+='                </div>';
			str+='            </div>';
			str+='            <div class="footer_copy">';
			str+='                <div class="container">';
			str+='                    <div class="column one">';
			str+='                        <div class="copyright">';
			str+='                            &copy; 2012 BeFootball  足球分析软件';
			str+='                        </div>';
			str+='                    </div>';
			str+='                </div>';
			str+='            </div>';
			str+='        </footer>';
			str+='    </div>';
			str+='     <div id="Side_slide" class="right dark" data-width="250">';
			str+='        <div class="close-wrapper">';
			str+='            <a href="#" class="close"><i class="icon-cancel-fine"></i></a>';
			str+='        </div>';
			str+='        <div class="menu_wrapper"></div>';
			str+='    </div>';
			str+='    <div id="body_overlay"></div>';



		$("#index_body").prepend(str);
		

	};


	return {
		init: function () {
			initBT();
		}
	};
}();

jQuery(document).ready(function() {
	initIndex.init();
});
var revapi1, tpj;
( function() {
	if (!/loaded|interactive|complete/.test(document.readyState))
		document.addEventListener("DOMContentLoaded", onLoad);
	else
		onLoad();
	function onLoad() {
		if (tpj === undefined) {
			tpj = jQuery;
			if ("off" == "on")
				tpj.noConflict();
		}
		if (tpj("#rev_slider_1_1").revolution == undefined) {
			revslider_showDoubleJqueryError("#rev_slider_1_1");
		} else {
			revapi1 = tpj("#rev_slider_1_1").show().revolution({
				sliderType : "hero",
				sliderLayout : "auto",
				dottedOverlay : "none",
				delay : 9000,
				visibilityLevels : [1240, 1024, 778, 480],
				gridwidth : 1080,
				gridheight : 900,
				lazyType : "none",
				parallax : {
					type : "scroll",
					origo : "enterpoint",
					speed : 400,
					speedbg : 0,
					speedls : 0,
					levels : [5, 10, 15, 20, 25, 30, 35, 40, 45, 46, 47, 48, 49, 50, 51, 55],
				},
				shadow : 0,
				spinner : "spinner2",
				autoHeight : "off",
				disableProgressBar : "on",
				hideThumbsOnMobile : "off",
				hideSliderAtLimit : 0,
				hideCaptionAtLimit : 0,
				hideAllCaptionAtLilmit : 0,
				debugMode : false,
				fallbacks : {
					simplifyAll : "off",
					disableFocusListener : false,
				}
			});
		};
	};
}());
